service: espnClone

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  apiKeys:
    - ${self:provider.stage}-apiKeyName1

  environment:
    baseUrl: 'https://www.thesportsdb.com/api/v1/json/1'

functions:
  list:
    handler: src/list.main
    events:
      - http:
          path: soccer/all
          method: get
          cors: true
          private: true
    memorySize: 128

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yaml)}